import type { CompanyDetail, Vehicle, Review, FinancialSummary } from "./types";

// ─── Mock Company Details (keyed by company ID) ──────────────────────────────

export const mockCompanyDetails: Record<string, CompanyDetail> = {
  co_01: {
    id: "co_01",
    name: "Apex Rentals Ltd.",
    slug: "apex-rentals",
    status: "active",
    owner: {
      name: "Amina Noor",
      email: "amina@apexrentals.com",
      phone: "+254 712 345 678",
    },
    contactEmail: "info@apexrentals.com",
    contactPhone: "+254 720 000 111",
    address: {
      street: "45 Kenyatta Avenue",
      city: "Nairobi",
      state: "Nairobi County",
      country: "Kenya",
      zip: "00100",
    },
    registrationDate: "2025-06-14",
    verificationStatus: "verified",
    totalVehicles: 24,
    totalBookings: 312,
    averageRating: 4.7,
    totalReviews: 89,
  },
  co_02: {
    id: "co_02",
    name: "Drive360 Solutions",
    slug: "drive360",
    status: "active",
    owner: {
      name: "Marcus Lee",
      email: "marcus@drive360.io",
      phone: "+27 82 456 7890",
    },
    contactEmail: "support@drive360.io",
    contactPhone: "+27 82 000 222",
    address: {
      street: "12 Sandton Drive",
      city: "Johannesburg",
      state: "Gauteng",
      country: "South Africa",
      zip: "2196",
    },
    registrationDate: "2025-09-02",
    verificationStatus: "verified",
    totalVehicles: 16,
    totalBookings: 187,
    averageRating: 4.3,
    totalReviews: 52,
  },
  co_03: {
    id: "co_03",
    name: "Nomad Fleet Co.",
    slug: "nomad-fleet",
    status: "suspended",
    owner: {
      name: "Sofia Alvarez",
      email: "sofia@nomadfleet.com",
      phone: "+234 801 234 5678",
    },
    contactEmail: "hello@nomadfleet.com",
    contactPhone: "+234 800 333 444",
    address: {
      street: "8 Victoria Island Rd",
      city: "Lagos",
      state: "Lagos State",
      country: "Nigeria",
      zip: "101001",
    },
    registrationDate: "2025-11-19",
    verificationStatus: "unverified",
    totalVehicles: 5,
    totalBookings: 43,
    averageRating: 3.8,
    totalReviews: 14,
  },
  co_04: {
    id: "co_04",
    name: "SwiftWheels Inc.",
    slug: "swiftwheels",
    status: "pending",
    owner: {
      name: "Eliot Chen",
      email: "eliot@swiftwheels.com",
      phone: "+233 50 678 9012",
    },
    contactEmail: "contact@swiftwheels.com",
    contactPhone: "+233 50 000 555",
    address: {
      street: "22 Independence Ave",
      city: "Accra",
      state: "Greater Accra",
      country: "Ghana",
      zip: "GA-100",
    },
    registrationDate: "2026-01-08",
    verificationStatus: "pending",
    totalVehicles: 0,
    totalBookings: 0,
    averageRating: 0,
    totalReviews: 0,
  },
  co_05: {
    id: "co_05",
    name: "Prism AutoGroup",
    slug: "prism-auto",
    status: "active",
    owner: {
      name: "Priya Singh",
      email: "priya@prismgroup.com",
      phone: "+20 100 234 5678",
    },
    contactEmail: "fleet@prismgroup.com",
    contactPhone: "+20 100 000 666",
    address: {
      street: "15 Tahrir Square",
      city: "Cairo",
      state: "Cairo Governorate",
      country: "Egypt",
      zip: "11511",
    },
    registrationDate: "2025-04-21",
    verificationStatus: "verified",
    totalVehicles: 38,
    totalBookings: 524,
    averageRating: 4.9,
    totalReviews: 142,
  },
};

// ─── Mock Vehicles ───────────────────────────────────────────────────────────

export const mockVehicles: Record<string, Vehicle[]> = {
  co_01: [
    {
      id: "v_01",
      name: "Toyota Land Cruiser",
      model: "Prado TX",
      year: 2024,
      plateNumber: "KDA 123A",
      status: "available",
      rentalRate: 120,
      mileage: 12400,
      fuelType: "Diesel",
      transmission: "Automatic",
    },
    {
      id: "v_02",
      name: "Mercedes-Benz",
      model: "E-Class 300",
      year: 2023,
      plateNumber: "KDB 456B",
      status: "rented",
      rentalRate: 200,
      mileage: 28500,
      fuelType: "Petrol",
      transmission: "Automatic",
    },
    {
      id: "v_03",
      name: "Nissan X-Trail",
      model: "ST-L",
      year: 2024,
      plateNumber: "KDC 789C",
      status: "available",
      rentalRate: 85,
      mileage: 8200,
      fuelType: "Petrol",
      transmission: "CVT",
    },
    {
      id: "v_04",
      name: "Range Rover",
      model: "Sport HSE",
      year: 2023,
      plateNumber: "KDD 012D",
      status: "maintenance",
      rentalRate: 280,
      mileage: 34700,
      fuelType: "Diesel",
      transmission: "Automatic",
    },
    {
      id: "v_05",
      name: "Toyota Hilux",
      model: "Double Cab",
      year: 2024,
      plateNumber: "KDE 345E",
      status: "available",
      rentalRate: 95,
      mileage: 5600,
      fuelType: "Diesel",
      transmission: "Manual",
    },
    {
      id: "v_06",
      name: "BMW 5 Series",
      model: "530i",
      year: 2023,
      plateNumber: "KDF 678F",
      status: "rented",
      rentalRate: 180,
      mileage: 19300,
      fuelType: "Petrol",
      transmission: "Automatic",
    },
    {
      id: "v_07",
      name: "Suzuki Jimny",
      model: "GLX",
      year: 2024,
      plateNumber: "KDG 901G",
      status: "available",
      rentalRate: 65,
      mileage: 3100,
      fuelType: "Petrol",
      transmission: "Automatic",
    },
    {
      id: "v_08",
      name: "Audi Q7",
      model: "Premium Plus",
      year: 2023,
      plateNumber: "KDH 234H",
      status: "rented",
      rentalRate: 250,
      mileage: 42100,
      fuelType: "Diesel",
      transmission: "Automatic",
    },
  ],
  co_02: [
    {
      id: "v_09",
      name: "Volkswagen Polo",
      model: "TSI",
      year: 2024,
      plateNumber: "GP 12 ABCD",
      status: "available",
      rentalRate: 45,
      mileage: 6700,
      fuelType: "Petrol",
      transmission: "Automatic",
    },
    {
      id: "v_10",
      name: "Ford Ranger",
      model: "Wildtrak",
      year: 2023,
      plateNumber: "GP 34 EFGH",
      status: "rented",
      rentalRate: 110,
      mileage: 31200,
      fuelType: "Diesel",
      transmission: "Automatic",
    },
    {
      id: "v_11",
      name: "Hyundai Tucson",
      model: "Elite",
      year: 2024,
      plateNumber: "GP 56 IJKL",
      status: "available",
      rentalRate: 75,
      mileage: 9400,
      fuelType: "Petrol",
      transmission: "Automatic",
    },
    {
      id: "v_12",
      name: "Toyota Fortuner",
      model: "2.8 GD-6",
      year: 2023,
      plateNumber: "GP 78 MNOP",
      status: "maintenance",
      rentalRate: 130,
      mileage: 45800,
      fuelType: "Diesel",
      transmission: "Automatic",
    },
  ],
  co_03: [
    {
      id: "v_13",
      name: "Honda CR-V",
      model: "EX-L",
      year: 2023,
      plateNumber: "LSR 123AA",
      status: "available",
      rentalRate: 70,
      mileage: 15200,
      fuelType: "Petrol",
      transmission: "CVT",
    },
    {
      id: "v_14",
      name: "Toyota Corolla",
      model: "LE",
      year: 2024,
      plateNumber: "LSR 456BB",
      status: "rented",
      rentalRate: 50,
      mileage: 4300,
      fuelType: "Petrol",
      transmission: "CVT",
    },
  ],
  co_04: [],
  co_05: [
    {
      id: "v_15",
      name: "BMW X5",
      model: "xDrive40i",
      year: 2024,
      plateNumber: "CAI 111A",
      status: "available",
      rentalRate: 220,
      mileage: 7800,
      fuelType: "Petrol",
      transmission: "Automatic",
    },
    {
      id: "v_16",
      name: "Mercedes-Benz",
      model: "GLE 450",
      year: 2023,
      plateNumber: "CAI 222B",
      status: "rented",
      rentalRate: 260,
      mileage: 21500,
      fuelType: "Petrol",
      transmission: "Automatic",
    },
    {
      id: "v_17",
      name: "Audi A6",
      model: "55 TFSI",
      year: 2024,
      plateNumber: "CAI 333C",
      status: "available",
      rentalRate: 190,
      mileage: 5200,
      fuelType: "Petrol",
      transmission: "Automatic",
    },
    {
      id: "v_18",
      name: "Porsche Cayenne",
      model: "S",
      year: 2023,
      plateNumber: "CAI 444D",
      status: "rented",
      rentalRate: 350,
      mileage: 18900,
      fuelType: "Petrol",
      transmission: "Automatic",
    },
    {
      id: "v_19",
      name: "Land Rover",
      model: "Defender 110",
      year: 2024,
      plateNumber: "CAI 555E",
      status: "maintenance",
      rentalRate: 280,
      mileage: 33400,
      fuelType: "Diesel",
      transmission: "Automatic",
    },
    {
      id: "v_20",
      name: "Lexus RX",
      model: "350 Premium",
      year: 2023,
      plateNumber: "CAI 666F",
      status: "available",
      rentalRate: 200,
      mileage: 11200,
      fuelType: "Petrol",
      transmission: "Automatic",
    },
  ],
};

// ─── Mock Reviews ────────────────────────────────────────────────────────────

export const mockReviews: Record<string, Review[]> = {
  co_01: [
    {
      id: "r_01",
      customerName: "John Kimani",
      rating: 5,
      comment:
        "Absolutely exceptional service! The Land Cruiser was spotless and performed perfectly on our safari trip. Will definitely rent again.",
      date: "2026-02-15",
      vehicleName: "Toyota Land Cruiser",
      flagged: false,
    },
    {
      id: "r_02",
      customerName: "Sarah Wanjiku",
      rating: 4,
      comment:
        "Good experience overall. The car was clean and the pickup process was smooth. Minor delay at drop-off but nothing major.",
      date: "2026-02-10",
      vehicleName: "Mercedes-Benz E-Class",
      flagged: false,
    },
    {
      id: "r_03",
      customerName: "David Ochieng",
      rating: 5,
      comment:
        "The BMW was in perfect condition. Professional staff and seamless booking experience. Highly recommend Apex Rentals.",
      date: "2026-02-05",
      vehicleName: "BMW 5 Series",
      flagged: false,
    },
    {
      id: "r_04",
      customerName: "Grace Muthoni",
      rating: 3,
      comment:
        "The vehicle was good but there was a minor scratch that wasn't mentioned. Customer service handled it well though.",
      date: "2026-01-28",
      vehicleName: "Nissan X-Trail",
      flagged: false,
    },
    {
      id: "r_05",
      customerName: "Peter Njoroge",
      rating: 5,
      comment:
        "Third time renting from Apex. Consistently excellent vehicles and service. The Jimny was perfect for city driving.",
      date: "2026-01-20",
      vehicleName: "Suzuki Jimny",
      flagged: false,
    },
    {
      id: "r_06",
      customerName: "Anonymous User",
      rating: 1,
      comment: "This is fake spam review content for testing moderation.",
      date: "2026-01-15",
      vehicleName: "Toyota Hilux",
      flagged: true,
    },
    {
      id: "r_07",
      customerName: "Lucy Akinyi",
      rating: 4,
      comment:
        "Great SUV for family trips. The Audi Q7 had plenty of space and was very comfortable on long drives.",
      date: "2026-01-10",
      vehicleName: "Audi Q7",
      flagged: false,
    },
    {
      id: "r_08",
      customerName: "James Mutua",
      rating: 5,
      comment:
        "Range Rover was a dream to drive. Worth every penny. Apex maintains their fleet impeccably.",
      date: "2026-01-05",
      vehicleName: "Range Rover Sport",
      flagged: false,
    },
    {
      id: "r_09",
      customerName: "Faith Ngina",
      rating: 4,
      comment:
        "Very reliable rental service. The Hilux handled off-road terrain beautifully.",
      date: "2025-12-28",
      vehicleName: "Toyota Hilux",
      flagged: false,
    },
    {
      id: "r_10",
      customerName: "Brian Kipchoge",
      rating: 5,
      comment:
        "Flawless from booking to return. The Mercedes E-Class exceeded expectations.",
      date: "2025-12-20",
      vehicleName: "Mercedes-Benz E-Class",
      flagged: false,
    },
    {
      id: "r_11",
      customerName: "Wafula Simiyu",
      rating: 2,
      comment:
        "Car was delivered late and had low fuel. Expected better from a premium service.",
      date: "2025-12-15",
      vehicleName: "Toyota Land Cruiser",
      flagged: false,
    },
    {
      id: "r_12",
      customerName: "Esther Kamau",
      rating: 5,
      comment:
        "Outstanding! The entire team at Apex is professional and the vehicles are always in top condition.",
      date: "2025-12-10",
      vehicleName: "BMW 5 Series",
      flagged: false,
    },
  ],
  co_02: [
    {
      id: "r_13",
      customerName: "Thabo Molefe",
      rating: 4,
      comment:
        "Solid service from Drive360. The Ranger handled the bushveld roads well.",
      date: "2026-02-12",
      vehicleName: "Ford Ranger",
      flagged: false,
    },
    {
      id: "r_14",
      customerName: "Naledi Khumalo",
      rating: 5,
      comment:
        "Best rental experience in Joburg. The Tucson was fuel-efficient and comfortable.",
      date: "2026-02-01",
      vehicleName: "Hyundai Tucson",
      flagged: false,
    },
    {
      id: "r_15",
      customerName: "Sipho Nkosi",
      rating: 3,
      comment:
        "The Polo was smaller than expected for the price. Service was fine otherwise.",
      date: "2026-01-22",
      vehicleName: "Volkswagen Polo",
      flagged: false,
    },
    {
      id: "r_16",
      customerName: "Lindiwe Zulu",
      rating: 5,
      comment:
        "Rented the Fortuner for a family road trip to Durban. Perfect vehicle, great support.",
      date: "2026-01-14",
      vehicleName: "Toyota Fortuner",
      flagged: false,
    },
  ],
  co_03: [
    {
      id: "r_17",
      customerName: "Chidi Okafor",
      rating: 4,
      comment:
        "Good car, fair price. The CR-V was comfortable for Lagos traffic.",
      date: "2026-01-25",
      vehicleName: "Honda CR-V",
      flagged: false,
    },
    {
      id: "r_18",
      customerName: "Amara Diallo",
      rating: 3,
      comment:
        "Average experience. Car was clean but the AC wasn't cooling well enough.",
      date: "2026-01-10",
      vehicleName: "Toyota Corolla",
      flagged: false,
    },
  ],
  co_04: [],
  co_05: [
    {
      id: "r_19",
      customerName: "Omar Hassan",
      rating: 5,
      comment:
        "The Porsche Cayenne was incredible. Prism AutoGroup offers luxury at its finest.",
      date: "2026-02-20",
      vehicleName: "Porsche Cayenne",
      flagged: false,
    },
    {
      id: "r_20",
      customerName: "Fatima El-Sayed",
      rating: 5,
      comment:
        "Absolutely premium service. The BMW X5 was flawless and the staff was incredibly professional.",
      date: "2026-02-14",
      vehicleName: "BMW X5",
      flagged: false,
    },
    {
      id: "r_21",
      customerName: "Ahmed Mostafa",
      rating: 4,
      comment:
        "Great selection of luxury vehicles. The Audi A6 was a pleasure to drive around Cairo.",
      date: "2026-02-08",
      vehicleName: "Audi A6",
      flagged: false,
    },
    {
      id: "r_22",
      customerName: "Layla Ibrahim",
      rating: 5,
      comment:
        "The GLE 450 was perfect for our family getaway. Top-notch quality and service.",
      date: "2026-02-02",
      vehicleName: "Mercedes-Benz GLE 450",
      flagged: false,
    },
    {
      id: "r_23",
      customerName: "Youssef Karim",
      rating: 5,
      comment:
        "The Lexus RX is silky smooth. Prism maintains their cars better than dealerships.",
      date: "2026-01-26",
      vehicleName: "Lexus RX 350",
      flagged: false,
    },
    {
      id: "r_24",
      customerName: "Nour Abdel",
      rating: 4,
      comment:
        "Excellent fleet and responsive customer support. The Defender was an adventure machine.",
      date: "2026-01-18",
      vehicleName: "Land Rover Defender",
      flagged: false,
    },
  ],
};

// ─── Mock Financial Summaries ────────────────────────────────────────────────

export const mockFinancials: Record<string, FinancialSummary> = {
  co_01: {
    totalBookings: 312,
    totalRevenue: 187400,
    pendingPayments: 12500,
    completedPayments: 174900,
    avgBookingValue: 601,
    revenueByMonth: [
      { month: "Sep", revenue: 18200, bookings: 28 },
      { month: "Oct", revenue: 22100, bookings: 35 },
      { month: "Nov", revenue: 19800, bookings: 30 },
      { month: "Dec", revenue: 28700, bookings: 45 },
      { month: "Jan", revenue: 24300, bookings: 38 },
      { month: "Feb", revenue: 21500, bookings: 32 },
    ],
    recentTransactions: [
      {
        id: "t_01",
        date: "2026-02-27",
        customerName: "John Kimani",
        vehicleName: "Toyota Land Cruiser",
        amount: 720,
        status: "completed",
      },
      {
        id: "t_02",
        date: "2026-02-25",
        customerName: "Sarah Wanjiku",
        vehicleName: "Mercedes-Benz E-Class",
        amount: 1200,
        status: "completed",
      },
      {
        id: "t_03",
        date: "2026-02-24",
        customerName: "David Ochieng",
        vehicleName: "BMW 5 Series",
        amount: 900,
        status: "pending",
      },
      {
        id: "t_04",
        date: "2026-02-22",
        customerName: "Grace Muthoni",
        vehicleName: "Nissan X-Trail",
        amount: 510,
        status: "completed",
      },
      {
        id: "t_05",
        date: "2026-02-20",
        customerName: "Peter Njoroge",
        vehicleName: "Suzuki Jimny",
        amount: 390,
        status: "refunded",
      },
      {
        id: "t_06",
        date: "2026-02-18",
        customerName: "Lucy Akinyi",
        vehicleName: "Audi Q7",
        amount: 1500,
        status: "completed",
      },
    ],
  },
  co_02: {
    totalBookings: 187,
    totalRevenue: 98300,
    pendingPayments: 7200,
    completedPayments: 91100,
    avgBookingValue: 526,
    revenueByMonth: [
      { month: "Sep", revenue: 11200, bookings: 18 },
      { month: "Oct", revenue: 14500, bookings: 22 },
      { month: "Nov", revenue: 13100, bookings: 20 },
      { month: "Dec", revenue: 19800, bookings: 32 },
      { month: "Jan", revenue: 16400, bookings: 26 },
      { month: "Feb", revenue: 12800, bookings: 19 },
    ],
    recentTransactions: [
      {
        id: "t_07",
        date: "2026-02-26",
        customerName: "Thabo Molefe",
        vehicleName: "Ford Ranger",
        amount: 660,
        status: "completed",
      },
      {
        id: "t_08",
        date: "2026-02-23",
        customerName: "Naledi Khumalo",
        vehicleName: "Hyundai Tucson",
        amount: 450,
        status: "pending",
      },
      {
        id: "t_09",
        date: "2026-02-21",
        customerName: "Sipho Nkosi",
        vehicleName: "Volkswagen Polo",
        amount: 270,
        status: "completed",
      },
    ],
  },
  co_03: {
    totalBookings: 43,
    totalRevenue: 18900,
    pendingPayments: 3400,
    completedPayments: 15500,
    avgBookingValue: 440,
    revenueByMonth: [
      { month: "Sep", revenue: 2100, bookings: 5 },
      { month: "Oct", revenue: 3200, bookings: 7 },
      { month: "Nov", revenue: 2800, bookings: 6 },
      { month: "Dec", revenue: 4500, bookings: 10 },
      { month: "Jan", revenue: 3600, bookings: 8 },
      { month: "Feb", revenue: 2700, bookings: 7 },
    ],
    recentTransactions: [
      {
        id: "t_10",
        date: "2026-02-24",
        customerName: "Chidi Okafor",
        vehicleName: "Honda CR-V",
        amount: 420,
        status: "completed",
      },
      {
        id: "t_11",
        date: "2026-02-19",
        customerName: "Amara Diallo",
        vehicleName: "Toyota Corolla",
        amount: 300,
        status: "pending",
      },
    ],
  },
  co_04: {
    totalBookings: 0,
    totalRevenue: 0,
    pendingPayments: 0,
    completedPayments: 0,
    avgBookingValue: 0,
    revenueByMonth: [],
    recentTransactions: [],
  },
  co_05: {
    totalBookings: 524,
    totalRevenue: 345200,
    pendingPayments: 18700,
    completedPayments: 326500,
    avgBookingValue: 659,
    revenueByMonth: [
      { month: "Sep", revenue: 38200, bookings: 56 },
      { month: "Oct", revenue: 45100, bookings: 68 },
      { month: "Nov", revenue: 41300, bookings: 62 },
      { month: "Dec", revenue: 62800, bookings: 95 },
      { month: "Jan", revenue: 51400, bookings: 78 },
      { month: "Feb", revenue: 44200, bookings: 65 },
    ],
    recentTransactions: [
      {
        id: "t_12",
        date: "2026-02-27",
        customerName: "Omar Hassan",
        vehicleName: "Porsche Cayenne",
        amount: 2100,
        status: "completed",
      },
      {
        id: "t_13",
        date: "2026-02-25",
        customerName: "Fatima El-Sayed",
        vehicleName: "BMW X5",
        amount: 1320,
        status: "completed",
      },
      {
        id: "t_14",
        date: "2026-02-23",
        customerName: "Ahmed Mostafa",
        vehicleName: "Audi A6",
        amount: 1140,
        status: "pending",
      },
      {
        id: "t_15",
        date: "2026-02-21",
        customerName: "Layla Ibrahim",
        vehicleName: "Mercedes-Benz GLE 450",
        amount: 1560,
        status: "completed",
      },
      {
        id: "t_16",
        date: "2026-02-19",
        customerName: "Youssef Karim",
        vehicleName: "Lexus RX 350",
        amount: 1200,
        status: "completed",
      },
    ],
  },
};

// ─── Lookup helper ───────────────────────────────────────────────────────────

/** Falls back to co_01 data for unknown IDs so the page always renders something. */
export function getCompanyData(companyId: string) {
  const id = mockCompanyDetails[companyId] ? companyId : "co_01";
  return {
    company: mockCompanyDetails[id],
    vehicles: mockVehicles[id] ?? [],
    reviews: mockReviews[id] ?? [],
    financials: mockFinancials[id],
  };
}
