import type { VehicleFullDetail, VehicleTrip } from "./types";

export const mockVehicleData: Record<string, VehicleFullDetail> = {
  list_1: {
    id: "list_1",
    hostId: "p2p_01",
    title: "2021 Toyota RAV4",
    category: "SUV",
    plateNumber: "KDG 123A",
    vin: "JTMDF5BX0MD******",
    year: 2021,
    make: "Toyota",
    model: "RAV4",
    color: "Silver",
    mileage: 45000,
    transmission: "automatic",
    fuelType: "petrol",
    seats: 5,
    dailyRate: 65,
    status: "unlisted",
    images: [],
    features: [
      "Air Conditioning",
      "Bluetooth",
      "Backup Camera",
      "Apple CarPlay",
      "Android Auto",
    ],
    description:
      "Well maintained Toyota RAV4, perfect for city and upcountry trips. Leather interior with all standard safety features working perfectly.",
    insuranceExpiry: "2026-10-15",
    lastServiced: "2025-11-20",
  },
  list_2: {
    id: "list_2",
    hostId: "p2p_03",
    title: "2020 Ford Ranger",
    category: "Pickup",
    plateNumber: "GW 4567-20",
    vin: "1FTER4EH6KL******",
    year: 2020,
    make: "Ford",
    model: "Ranger",
    color: "Black",
    mileage: 62000,
    transmission: "manual",
    fuelType: "diesel",
    seats: 5,
    dailyRate: 78,
    status: "active",
    images: [],
    features: [
      "4WD/AWD",
      "Towing Package",
      "Bed Liner",
      "Bluetooth",
      "Backup Camera",
      "Navigation",
    ],
    description:
      "Rugged and reliable Ford Ranger Double Cabin. Excellent for hauling or off-road adventures. Routine service just completed.",
    insuranceExpiry: "2026-05-12",
    lastServiced: "2026-01-10",
  },
  list_3: {
    id: "list_3",
    hostId: "p2p_03",
    title: "2019 Toyota Corolla",
    category: "Sedan",
    plateNumber: "GR 8901-19",
    vin: "2T1BURHE1JC******",
    year: 2019,
    make: "Toyota",
    model: "Corolla",
    color: "White",
    mileage: 78000,
    transmission: "automatic",
    fuelType: "petrol",
    seats: 5,
    dailyRate: 45,
    status: "active",
    images: [],
    features: ["Air Conditioning", "Bluetooth", "USB Charger"],
    description:
      "Fuel-efficient daily driver. Very clean interior and cold AC. Ideal for running errands around the city.",
    insuranceExpiry: "2026-08-30",
    lastServiced: "2026-02-01",
  },
};

export const mockVehicleTrips: Record<string, VehicleTrip[]> = {
  list_1: [],
  list_2: [
    {
      id: "trip_1",
      renterName: "Alice M.",
      startDate: "2026-02-20",
      endDate: "2026-02-23",
      amount: 234.0,
      status: "completed",
      rating: 5,
    },
    {
      id: "trip_2",
      renterName: "Bob N.",
      startDate: "2026-02-10",
      endDate: "2026-02-14",
      amount: 312.0,
      status: "completed",
      rating: 4,
    },
    {
      id: "trip_3",
      renterName: "Charlie K.",
      startDate: "2026-03-05",
      endDate: "2026-03-10",
      amount: 390.0,
      status: "upcoming",
    },
  ],
  list_3: [
    {
      id: "trip_4",
      renterName: "David O.",
      startDate: "2026-02-18",
      endDate: "2026-02-20",
      amount: 90.0,
      status: "completed",
      rating: 5,
    },
    {
      id: "trip_5",
      renterName: "Eva L.",
      startDate: "2026-02-05",
      endDate: "2026-02-09",
      amount: 180.0,
      status: "completed",
      rating: 5,
    },
  ],
};

export function getVehicleData(vehicleId: string) {
  const id = mockVehicleData[vehicleId] ? vehicleId : "list_2";
  return {
    vehicle: mockVehicleData[id],
    trips: mockVehicleTrips[id] || [],
  };
}
